### ISSUE TITLE
vscode 本地调试 云函数出错

### ISSUE THREAD

**Issue by Yang-yibu** [ksky521/fresh-weather#1]
1 代码中有从数据库获取数据；在 vscode 中 报错
`Error: errCode: -1 unknown error \| errMsg: document.get:fail Error: missing secretId or secretKey of tencent cloud; at document.get api;`
不知道接下来该如何进行了；

2 在控制台的日志中，makeImage 函数中的 console.log 打印不出来

![image](https://user-images.githubusercontent.com/23130670/46245358-fbf4fd80-c41e-11e8-8b02-73a307ddee10.png)

**Comment by ksky521** [comment]
看提示是没有配置 skey 和 key 呀，你这个应该是用了腾讯云的接口吧，接口本地调用可能会有问题

**Comment by sqh17** [comment]
在运行npm run cloud时，报错。

![pic](https://user-images.githubusercontent.com/25773838/46590641-5eb55b80-cae7-11e8-8759-b67fb70dd516.PNG)

**Comment by Yang-yibu** [comment]
> 看提示是没有配置 skey 和 key 呀，你这个应该是用了腾讯云的接口吧，接口本地调用可能会有问题

对；我用了云开发的数据库；请问老师，有么有办法在什么地方配置下把他这个模拟的配上

**Comment by ksky521** [comment]
这个没法模拟
